version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"

  minio-init:
    image: minio/mc
    profiles: ["init"]
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until mc alias set local http://minio:9000 minio minio123; do
          echo 'waiting for minio' && sleep 1;
        done;
        if ! mc ls local/uploads >/dev/null 2>&1; then
          mc mb local/uploads;
        fi;
        exit 0;
      "


volumes:
  db-data:
  minio-data:
